### ISSUE TITLE
Issue in using code

### ISSUE THREAD

**Issue by zackrider-png** [Sean-Bradley/ECDSA_secp256k1_JordonMatrix_nodejs#17]
Hi sir i want to run this code but inorder to run this code i do have rsz values could u plz provide me that me that code plz sir.

**Comment by Sean-Bradley** [comment]
It costs me $100 a month to host a version of the blockchain that returns rsv values on demand. This isn't going to happen

**Comment by zackrider-png** [comment]
U can monetize and host google ads sir u can also earn some passive income sir, this is just a suggestion sir thank u
