### ISSUE TITLE
How to find " K " and " X " ??

### ISSUE THREAD

**Issue by nandandoloxz** [Sean-Bradley/ECDSA_secp256k1_JordonMatrix_nodejs#2]
sir, can help me ??
 how to find " K " and " X "??
and this process with sage or what ?? give me tutorial. thanksyou. Best Regards

//proving K = ((Z + (X * R)) / S) % N
            var verifyK = Z.Add(X.Multiply(R)).Multiply(S.ModInverse(N)).Mod(N);
            Console.WriteLine("K = " + string.Concat(verifyK.ToByteArrayUnsigned().Select(b => b.ToString("X2"))));

**Comment by martinkh** [comment]
question: on the site 2coin, how did you complete /2 function on the private key to address page? Thanks

**Comment by Sean-Bradley** [comment]
I dont understand your question. Read the source.

**Comment by Sean-Bradley** [comment]
Why ate people creating issues for stupid questions?

**Comment by martinkh** [comment]
On your website, 2coin.org, how do you create the function /2 button on private key to bitcoin address? Thanks

**Comment by Sean-Bradley** [comment]
View the source, its a one liner.
