### ISSUE TITLE
Why site 2coin.org are not working?

### ISSUE THREAD

**Issue by amiwrcd** [Sean-Bradley/ECDSA_secp256k1_JordonMatrix_nodejs#4]
Hello Sean! Why site **2coin.org** are not working? See Get **R, S, Z** values. I can not get the values there are not generated.

**Comment by FdxDelveloper** [comment]
hello sean Why site 2coin.org are not working? See Get R, S, Z values. I can not get the values there are not generated. day ago  see Get R, S, Z values. it working  today not working

**Comment by FdxDelveloper** [comment]
i support you
