### ISSUE TITLE
2coin down.

### ISSUE THREAD

**Issue by troyam** [Sean-Bradley/ECDSA_secp256k1_JordonMatrix_nodejs#7]
Can you share the api?
I searched at web.archive.org but not found the scripts to find Z automatically.
Thks!

**Comment by Sean-Bradley** [comment]
No

**Comment by troyam** [comment]
![After 2 days working](https://user-images.githubusercontent.com/28970728/78471134-438bd200-7705-11ea-86fa-0bec4b1918c7.png)

After 2 days working...
So, how can I found similars transactions??

**Comment by troyam** [comment]
Good job with RMDstring !!! :D
